#!/usr/bin/env bash
# Build the docs/ directory for GitHub Pages deployment.
# Copies poc/ assets and rewrites the Ruffle path.
#
# Usage: ./scripts/build-pages.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DOCS="$REPO_ROOT/docs"
POC="$REPO_ROOT/poc"

# Clean previous build
rm -rf "$DOCS"
mkdir -p "$DOCS"

# Copy source files
cp "$POC/index.html" "$DOCS/"
cp -r "$POC/src" "$DOCS/"

# Copy SWFs (must have been generated by scripts/patch_swfs.sh)
if [ ! -d "$POC/swf" ] || [ -z "$(ls "$POC/swf"/*.swf 2>/dev/null)" ]; then
  echo "ERROR: No SWFs found in poc/swf/. Run scripts/patch_swfs.sh first."
  exit 1
fi
cp -r "$POC/swf" "$DOCS/"

# Copy Ruffle runtime
RUFFLE="$POC/node_modules/@ruffle-rs/ruffle"
if [ ! -f "$RUFFLE/ruffle.js" ]; then
  echo "ERROR: Ruffle not found. Run 'cd poc && npm install' first."
  exit 1
fi
mkdir -p "$DOCS/ruffle"
cp "$RUFFLE"/ruffle.js "$DOCS/ruffle/"
cp "$RUFFLE"/*.wasm "$DOCS/ruffle/" 2>/dev/null || true
cp "$RUFFLE"/*.js "$DOCS/ruffle/"
cp "$RUFFLE"/*.js.map "$DOCS/ruffle/" 2>/dev/null || true

# Rewrite Ruffle script path in index.html
sed -i '' 's|node_modules/@ruffle-rs/ruffle/ruffle.js|ruffle/ruffle.js|' "$DOCS/index.html"

echo "Built docs/ ($(du -sh "$DOCS" | cut -f1) total)"
echo "Next steps:"
echo "  1. git add docs/"
echo "  2. git commit -m 'Add GitHub Pages build'"
echo "  3. git remote add origin git@github.com:<user>/<repo>.git"
echo "  4. git push -u origin main"
echo "  5. Enable Pages in repo Settings → Pages → Source: main, /docs"
